### ISSUE TITLE
Fix/tidy up argument parsing

### ISSUE THREAD

**Issue by 4mig4** [Fizzadar/Luapress#74] opened 2019-06-28 15:31 UTC
With the new LuaPress 4.0 my previously working LuaPress 3.4 config does not work anymore
the `production` environnement is not taken into account and the site gets built in `./build` directory instead of `./production` directory when generated with `luapress --lhtml production`.

```
local config = {
	url = 'http://myserver',
	template = 'mytemplate',
	title = 'My Test',
	index_page = 'Home',
	posts_per_page = 3,
	discount_options = {'toc', 'extrafootnote', 'fencedcode'},
	envs = {
		production = {
			url = 'https://my-real.server.com',
			build_dir = 'production'
		}
	}
}
```

**Comment by Fizzadar** [comment] 2019-06-28 16:56
@4mig4 the `--lhtml` flag has now been renamed to `--template` - however it doesn't appear to parse args as intended:

```
# Works (fixes your issue)
luapress production --template lhtml

# Doesn't work
luapress --template lhtml production
```

**Comment by Fizzadar** [comment] 2019-08-23 09:01
This is fixed by https://github.com/Fizzadar/Luapress/commit/a7b776fad0cfa1d06227aa57ce7410933ba28dd8 + `v4.1.1`.

**Closed as completed by Fizzadar** 2019-08-23 09:01 UTC
Labels: bug
